[package]
name = "seqrepo"
version = "0.5.1"
edition = "2021"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Port of (read-only) functionality of biocommons/seqrepo to Rust"
license = "Apache-2.0"
homepage = "https://github.com/bihealth/seqrepo-rs"
readme = "README.md"

[lib]
name = "seqrepo"
path = "src/lib.rs"

[dependencies]
chrono = "0.4"
noodles-bgzf = "0.22"
noodles-core = "0.11"
noodles-fasta = "0.23"
rusqlite = "0.29"
thiserror = "1.0"
tracing = "0.1"

[dev-dependencies]
anyhow = "1.0"
clap-verbosity-flag = {version = "2.0"}
clap = { version = "4.1", features = ["derive", "env"] }
env_logger = "0.10"
log = "0.4"
pretty_assertions = "1.3"
temp_testdir = "0.2"
test-log = "0.2"
textwrap = "0.16"
tracing-subscriber = {version = "0.3" }
