[package]
name = "seqrepo"
version = "0.4.0"
edition = "2021"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Port of (read-only) functionality of biocommons/seqrepo to Rust"
license = "Apache-2.0"
homepage = "https://github.com/bihealth/seqrepo-rs"
readme = "README.md"

[lib]
name = "seqrepo"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.23"
log = "0.4.17"
noodles = { version = "0.39.0", features = ["bgzf", "fasta", "core"] }
rusqlite = "0.29.0"
strum = { version = "0.24.1", features = ["derive", "strum_macros"] }
textwrap = "0.16.0"
thiserror = "1.0.40"
tracing = "0.1.37"

[dev-dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.4", features = ["derive", "env"] }
clap-verbosity-flag = {version = "2.0.0"}
env_logger = "0.10.0"
pretty_assertions = "1.3.0"
temp_testdir = "0.2.3"
test-log = "0.2.11"
tracing-subscriber = {version = "0.3.16" }
